apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pricing-service
  template:
    metadata:
      labels:
        app: pricing-service
    spec:
      containers:
      - name: pricing-service
        image: yourdockerhubusername/pricing-service:latest
        ports:
        - containerPort: 3000
